### ISSUE TITLE
[Feature]: Add Routing to different pages through Navbar using React-Router

### ISSUE THREAD

**Issue by Prayas248** [OPCODE-Open-Spring-Fest/tri-api#1]
### So, what is it about?

Using React-Router, the contributor must add routing to different react components (Home, Cars,IMDB,Currency) through the Navbar Component.

### Code of Conduct

- [ ] I agree to follow this project's Code of Conduct

**Comment by sharvil-lade** [comment]
@Prayas248 Can you please assign this task to me

**Comment by xTwo56** [comment]
If assigned, I will use
i) useNavigate to minimize rerenders
ii) lazy for memory management

**Comment by Prayas248** [comment]
> @Prayas248 Can you please assign this task to me

Ok i am assigning this task to you
- you have 4 days of time to submit a pull request for this issue
- after this time, i would give this issue to any other contributor
- contact me on discord @sharvil-lade

**Comment by Prayas248** [comment]
> If assigned, I will use i) useNavigate to minimize rerenders ii) lazy for memory management

@xTwo56 
- if this issue is not resolved till the deadline given to @sharvil-lade , then i would i assign this task to you
- if this issue is closed, if you think that you can enhance this feature, then make sure to raise an issue or contact me on discord

**Comment by Prayas248** [comment]
@sharvil-lade has successfully solved this issue
