### ISSUE TITLE
[Feature]: Fetch the Cars API using the input paramaters.

### ISSUE THREAD

**Issue by Prayas248** [OPCODE-Open-Spring-Fest/tri-api#16]
### So, what is it about?

Fetch the Cars API using the two input parameters already taken in the cars input component.

Make sure to create a new component which would be rendered with the fetched information as soon as the user inputs the paramaters.

The API will be fetched in this new component named 'CarsFetch1.js' using the Axios instance already created in the CarsAPI.js file.

Make sure to change the header of the instance with your own header (only the header and not the baseURL)  that you will get when you activate the API, you can find more info about it in the README.md file, about how to activate the API

For any queries, do contact me on discord
### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by xTwo56** [comment]
Can I have this assignment

**Comment by satyamraj1643** [comment]
Kindly assign this to me @Prayas248 .

**Comment by Prayas248** [comment]
@xTwo56 and @satyamraj1643 are assigned to this issue.

Complete it in the next 7-8 days.

**Comment by neerajyadavrewa** [comment]
@Prayas248 please assign this to me
