### ISSUE TITLE
[Feature]: Fetch the Currency API.

### ISSUE THREAD

**Issue by Prayas248** [OPCODE-Open-Spring-Fest/tri-api#17]
### So, what is it about?

Just display the Currency API with address 'Supported Currencies'.
![Screenshot 2024-03-25 191541](https://github.com/OPCODE-Open-Spring-Fest/tri-api/assets/128613438/f9802393-895c-4a00-b9bb-77224fd69b01)

Fetch the Information about the different currencies along with the currency code.
Make sure you apply CSS to the fetched information
The information should be fetched inside the CurrencyAPI.js file using the Axios instance present in CurrencyAPI.js file
For any queries, contact me on discord

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by xTwo56** [comment]
Can I have this assignment

**Comment by Prayas248** [comment]
> Can I have this assignment

@xTwo56 is assigned this issue.
Complete it in the next 4-5 days

**Comment by neerajyadavrewa** [comment]
@Prayas248 please assign this to me
