### ISSUE TITLE
[Feature]: Create a Home Page that would give brief intro about the 3 API's.

### ISSUE THREAD

**Issue by Prayas248** [OPCODE-Open-Spring-Fest/tri-api#3]
### So, what is it about?

The Home page should be created in the HomeCode.js file present inside the Home folder of the Component folder.
Usage of tailwind CSS is mandatory.
The Page should be Responsive.
No Extra Component should be made for creating the Home page ( i.e. the whole code should be present inside the HomeCode.js file and no extra JS file for component pursposes should be used in this case).

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by satyamraj1643** [comment]
@Prayas248 kindly assign this feature to me.


- Ok you will be assigned this issue
- you have 2 days from tomorrow to submit the PR for this issue
- For any issue related queries, do contact me on Discord

**Comment by Prayas248** [comment]
@satyamraj1643 successfully solved this issue.
