### ISSUE TITLE
[Feature]: Create a Footer.

### ISSUE THREAD

**Issue by Prayas248** [OPCODE-Open-Spring-Fest/tri-api#4]
### So, what is it about?

A NEW folder should be made inside the Component folder named as "Footer".
Inside the a file name "FooterCode.js" should be created and the footer component should be made in that file only.

Description:
The Footer should include the links to the 3 API's given , and should mention OSF (Open Spring Fest) and any other info that according to you might make sense in the footer section.
Usage of Tailwind CSS is mandatory.
Footer must be responsive.
No extra components must be created other than the single file "FooterCode.js"

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by sharvil-lade** [comment]
@Prayas248 Can you please assign this task to me

**Comment by Prayas248** [comment]
> @Prayas248 Can you please assign this task to me

> * Ok you will be assigned this issue
> * you have 2 days from today to submit the PR for this issue
> * For any issue related queries, do contact me on Discord

**Comment by Prayas248** [comment]
@sharvil-lade has successfully solved this issue
