### ISSUE TITLE
[Feature]: Input bar creation with proper functionality for giving params input to the Cars API only.

### ISSUE THREAD

**Issue by Prayas248** [OPCODE-Open-Spring-Fest/tri-api#5]
### So, what is it about?

Create 2 proper responsive Input bar with a single button for accepting the inputs
Tailwind CSS should be used.
A new Component should be made for this purpose inside the Cars folder which is inside the component folder.
A button should be created inside the 'CarsCode.js' file through which the user should be able to Render the new Component that you would create. (NOTE- Do not use react router for this, just simply render your component (toggle) on click of the button.
The already present file of 'CarsCode.js' should be able to route to your component.

![Screenshot 2024-03-21 161807](https://github.com/OPCODE-Open-Spring-Fest/tri-api/assets/128613438/94a57cbe-c621-4bb9-8aae-7147828d5e48)

the user should input the params "limit" and "page" for the specific API route as shown above and update the necessary variables.
As these variables will be used as parameters for fetching the API

NOTE- You don't have to fetch any API, but just create 2 vairables that would then be used to fetch the API.

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by satyamraj1643** [comment]
@Prayas248 i want to contribute to this repo, kindly assign this to me.

**Comment by Prayas248** [comment]
> @Prayas248 i want to contribute to this repo, kindly assign this to me.

- Ok you will be assigned this issue
- you have 4 days from tomorrow to submit the PR for this issue
- For any issue related queries, do contact me on Discord.

**Comment by satyamraj1643** [comment]
@Prayas248  So basically, one component will be input component which will be triggered when user click on a button in CarsCode.js?

**Comment by Prayas248** [comment]
@satyamraj1643 successfully solved this issue.
