### ISSUE TITLE
[Feature]: Creating Axios instance for Currency API.

### ISSUE THREAD

**Issue by Prayas248** [OPCODE-Open-Spring-Fest/tri-api#8]
### So, what is it about?

Create an axios instance of the Currency API in the "CurrencyAPI.js" file which is inside the Currency folder, which is intern inside the Components folder.
Use "axios.create()" for creating a new axios instance of the base URL of the API that inherits all properties of axios.
This instance should be exported as it would then be used by "CurrencyCode.js" file for fetching the data.

NOTE-- Follow the steps described in README.md file for activating the API before creating its instance.

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by xTwo56** [comment]
@Prayas248 Please assign me this issue

**Comment by Prayas248** [comment]
> @Prayas248 Please assign me this issue

- Ok i am assigning you this issue @xTwo56 
- Your deadline would be after 2 days,  that is,  you have to submit a pull request within the next 2 days.
- Don't submit it right away, take atleast 1 day to submit your PR.

**Comment by Prayas248** [comment]
@xTwo56 completed this issue
